apiVersion: v1
kind: Service
metadata:
  name: bookshelf-app
  namespace: bookshelf
spec:
  type: NodePort
  selector:
    app: bookshelf-app
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 32400
